apiVersion: apps/v1
kind: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-ns
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  strategy: 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: 376672410739.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2:assign2-mysql
          name: mysql
          ports:
          - containerPort: 3306
          - name: MYSQL_ROOT_PASSWORD
            value: passwd123
