apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels: 
    name: webapp
spec:
  containers:
  - name: webapp
    image: 376672410739.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2/assign2-webapp
    ports:
      - containerPort: 8080
    imagePullSecrets:
      - name: assign2secret
